version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  flask:
    build: ./flask
    container_name: flask-app
    environment:
      - FLASK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=flaskuser
      - DATABASE_PASSWORD=flaskpassword
      - DATABASE_DB=flaskdb
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend
    command: gunicorn --bind 0.0.0.0:5000 -w 4 --timeout 90 wsgi:app

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:

