# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy the Nginx config file
COPY nginx.conf /etc/nginx/nginx.conf
#COPY conf.d/default.conf /etc/nginx/conf.d/default.conf
# Expose port 80
EXPOSE 80

